### ISSUE TITLE
How can we make it to detect emotion on real time?

### ISSUE THREAD

**Issue by Hina55** [lampadovnikita/EmotionRecognition#1]
I mean, no need to capture images, just process directly and it'll show emotion probabilities. Can you please update it in that way?

**Comment by lampadovnikita** [comment]
I think this is possible, but it requires a completely different approach to taking an image for processing by a neural network. This application uses an intent system to take a photo, and to complete your task you need to process images from a camera in real time. Maybe one or more images per second. This approach requires additional optimization. Unfortunately, I cannot fulfill your request, because at the moment I am busy with another project. Perhaps in the near future I will even archive this repository.
